[package]
name = "jlc"
version = "0.1.0"
edition = "2018"

[lib]
name = "jlc"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonlogic = "0.5.1"
peg = "0.7.0"
serde_json = "1.0.64"
